# Generated by Django 5.0.6 on 2024-06-26 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grapes_backend_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("annotated_image", models.TextField()),
                ("overall_maturity", models.CharField(max_length=11)),
                ("ph", models.FloatField()),
            ],
        ),
    ]
